version: '2'
services:
    blog-app:
        image: blog
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/eureka
            - SPRING_CLOUD_CONFIG_URI=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/config
            - SPRING_DATASOURCE_URL=jdbc:postgresql://blog-postgresql:5432/blog
            - JHIPSTER_SLEEP=30
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=blog-elasticsearch:9300
            - JHIPSTER_REGISTRY_PASSWORD=admin
        ports:
            - 8080:8080
    blog-postgresql:
        image: postgres:9.6.5
        environment:
            - POSTGRES_USER=blog
            - POSTGRES_PASSWORD=
    blog-elasticsearch:
        image: elasticsearch:2.4.6
    
    store-app:
        image: store
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/eureka
            - SPRING_CLOUD_CONFIG_URI=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/config
            - SPRING_DATA_MONGODB_URI=mongodb://store-mongodb:27017
            - SPRING_DATA_MONGODB_DATABASE=store
            - JHIPSTER_SLEEP=30
            - JHIPSTER_REGISTRY_PASSWORD=admin
    store-mongodb:
        image: mongo:3.4.10
    
    jhipster-registry:
        extends:
            file: jhipster-registry.yml
            service: jhipster-registry
